# qback configuration file

# Entry/exit times (in HH:MM format)
entry_times:
  - "09:16"
  # - "09:17"
  # - "09:23"
exit_times:
  - "15:21"
  # - "15:22"
  # - "15:17"

# Strike offsets (ATM, 1-4 OTM)
strike_offsets: [0, 1, 2, 3, 4]

# Option types
option_types: ["CE", "PE", "BOTH"]

# Max re-entries
max_re_entries: [4]

# Re-entry strategies
re_entry_types:
  # - RE-ASAP
  # - RE-ASAP_REVERSE
  # - RE-COST
  # - RE-COST_REVERSE
  - RE-MOMENTUM
  - RE-MOMENTUM_REVERSE

# Stop-loss types and their corresponding test values
stop_loss:
  percent_premium: [5, 10, 12] # % of Premium
  points: [5, 10, 25] # Premium Points (₹)
  points_index: [25, 45, 55] # Underlying Points
  percent_index: [0.8, 1.0, 1.4]  # Underlying % Move

# Fees and slippage
brokerage_per_trade: 20      # INR per trade (round trip)
slippage_perc: 0.005          # 0.5% entry/exit

# NIFTY strike interval
strike_interval: 50

# Initial position direction (False = SHORT, True = LONG)
initial_position_long: True

# Filtration criteria for viable strategies
filtration_criteria:
  min_roi: 50.0
  min_return_mdd: 4.0
  min_reward_risk: 1.1
  min_expectancy: 0.3
  min_win_rate: 55.0
  min_avg_profit_per_period: 0.1
  max_drawdown: 25.0

# Weights for composite score calculation
composite_score_weights:
  roi: 0.30
  return_mdd_ratio: 0.30
  win_rate: 0.20
  expectancy: 0.10
  avg_profit_per_period: 0.10
